# Generated by Django 5.1.15 on 2026-08-03 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_manager_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveIntegerField()),
                ('week', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(default='sleeper', max_length=32)),
                ('external_id', models.CharField(max_length=32)),
                ('player_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('espn_player_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('games', models.FloatField(blank=True, null=True)),
                ('pts_ppr', models.FloatField(blank=True, null=True)),
                ('pts_half_ppr', models.FloatField(blank=True, null=True)),
                ('pts_std', models.FloatField(blank=True, null=True)),
                ('adp', models.FloatField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections', to='league.player')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'position'], name='league_play_season_63e700_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'season', 'week', 'external_id'), name='uniq_projection_row')],
            },
        ),
    ]
