# Generated by Django 5.1.15 on 2026-07-14 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DraftPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveSmallIntegerField()),
                ("round_pick", models.PositiveSmallIntegerField()),
                ("overall_pick", models.PositiveSmallIntegerField()),
                ("is_keeper", models.BooleanField(default=False)),
                ("auction_price", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["season", "overall_pick"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_league_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("real_name", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_player_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(blank=True, max_length=8)),
                (
                    "gsis_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=64)),
                ("years", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("row_counts", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DraftPickValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_points", models.FloatField(default=0.0)),
                ("points_over_replacement", models.FloatField(default=0.0)),
                ("adp", models.FloatField(blank=True, null=True)),
                ("adp_delta", models.FloatField(blank=True, null=True)),
                ("round_expectation_delta", models.FloatField(default=0.0)),
                (
                    "draft_pick",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="value",
                        to="league.draftpick",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerCareerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seasons_played", models.PositiveSmallIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("ties", models.PositiveIntegerField(default=0)),
                ("championships", models.PositiveSmallIntegerField(default=0)),
                ("playoff_appearances", models.PositiveSmallIntegerField(default=0)),
                ("sackos", models.PositiveSmallIntegerField(default=0)),
                ("total_points_for", models.FloatField(default=0.0)),
                ("total_luck_delta", models.FloatField(default=0.0)),
                ("longest_win_streak", models.PositiveSmallIntegerField(default=0)),
                ("longest_lose_streak", models.PositiveSmallIntegerField(default=0)),
                ("extras", models.JSONField(blank=True, default=dict)),
                (
                    "manager",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_stats",
                        to="league.manager",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draftpick",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_picks",
                to="league.player",
            ),
        ),
        migrations.CreateModel(
            name="PlayerADP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season", models.PositiveIntegerField()),
                ("player_name", models.CharField(max_length=200)),
                ("position", models.CharField(blank=True, max_length=8)),
                ("adp", models.FloatField()),
                ("source", models.CharField(default="ffc", max_length=64)),
                ("fmt", models.CharField(default="standard", max_length=16)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season", "position"],
                        name="league_play_season_3122c4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RawSourcePayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="espn", max_length=32)),
                ("league_id", models.BigIntegerField(default=0)),
                ("year", models.PositiveIntegerField(default=0)),
                ("view", models.CharField(blank=True, max_length=64)),
                (
                    "scoring_period",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["league_id", "year"],
                        name="league_raws_league__32705c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "source",
                            "league_id",
                            "year",
                            "view",
                            "scoring_period",
                        ),
                        name="uniq_raw_payload",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("scoring_settings", models.JSONField(blank=True, default=dict)),
                ("roster_slots", models.JSONField(blank=True, default=dict)),
                ("regular_season_weeks", models.PositiveSmallIntegerField(default=0)),
                ("playoff_team_count", models.PositiveSmallIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                ("lineups_available", models.BooleanField(default=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="league.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AddField(
            model_name="draftpick",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_picks",
                to="league.season",
            ),
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("value", models.FloatField(default=0.0)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="league.manager",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awards",
                        to="league.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="league.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trends",
                        to="league.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamSeason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("espn_team_id", models.PositiveIntegerField()),
                ("team_name", models.CharField(blank=True, max_length=200)),
                ("abbrev", models.CharField(blank=True, max_length=16)),
                ("division", models.CharField(blank=True, max_length=100)),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                ("points_for", models.FloatField(default=0.0)),
                ("points_against", models.FloatField(default=0.0)),
                ("final_standing", models.PositiveSmallIntegerField(default=0)),
                ("made_playoffs", models.BooleanField(default=False)),
                (
                    "managers",
                    models.ManyToManyField(
                        related_name="team_seasons", to="league.manager"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_seasons",
                        to="league.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matchup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveSmallIntegerField()),
                ("home_score", models.FloatField(default=0.0)),
                ("away_score", models.FloatField(default=0.0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REG", "Regular season"),
                            ("PLAYOFF", "Playoff"),
                            ("CONSOLATION", "Consolation"),
                            ("CHAMPIONSHIP", "Championship"),
                            ("TOILET_BOWL", "Toilet bowl"),
                        ],
                        default="REG",
                        max_length=16,
                    ),
                ),
                ("is_bye", models.BooleanField(default=False)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchups",
                        to="league.season",
                    ),
                ),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matchups",
                        to="league.teamseason",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matchups",
                        to="league.teamseason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManagerSeasonStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins", models.PositiveSmallIntegerField(default=0)),
                ("losses", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                ("points_for", models.FloatField(default=0.0)),
                ("points_against", models.FloatField(default=0.0)),
                ("all_play_wins", models.FloatField(default=0.0)),
                ("all_play_games", models.FloatField(default=0.0)),
                ("expected_wins", models.FloatField(default=0.0)),
                ("luck_delta", models.FloatField(default=0.0)),
                ("points_against_percentile", models.FloatField(default=0.0)),
                ("weekly_score_stddev", models.FloatField(default=0.0)),
                ("optimal_points", models.FloatField(default=0.0)),
                ("bench_points_lost", models.FloatField(default=0.0)),
                ("lineup_efficiency", models.FloatField(default=0.0)),
                ("final_standing", models.PositiveSmallIntegerField(default=0)),
                ("made_playoffs", models.BooleanField(default=False)),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_stats",
                        to="league.manager",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_stats",
                        to="league.season",
                    ),
                ),
                (
                    "team_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_stats",
                        to="league.teamseason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LineupSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveSmallIntegerField()),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("QB", "QB"),
                            ("RB", "RB"),
                            ("WR", "WR"),
                            ("TE", "TE"),
                            ("FLEX", "FLEX"),
                            ("DST", "D/ST"),
                            ("K", "K"),
                            ("BE", "Bench"),
                            ("IR", "IR"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=8,
                    ),
                ),
                ("points", models.FloatField(default=0.0)),
                ("projected_points", models.FloatField(default=0.0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_slots",
                        to="league.player",
                    ),
                ),
                (
                    "team_season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_slots",
                        to="league.teamseason",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="draftpick",
            name="team_season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft_picks",
                to="league.teamseason",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ADD", "Add"),
                            ("DROP", "Drop"),
                            ("TRADE", "Trade"),
                            ("WAIVER", "Waiver"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=8,
                    ),
                ),
                ("bid_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("players", models.JSONField(blank=True, default=list)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="league.season",
                    ),
                ),
                (
                    "team_season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="league.teamseason",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeadToHeadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_wins", models.PositiveSmallIntegerField(default=0)),
                ("b_wins", models.PositiveSmallIntegerField(default=0)),
                ("ties", models.PositiveSmallIntegerField(default=0)),
                ("a_points", models.FloatField(default=0.0)),
                ("b_points", models.FloatField(default=0.0)),
                ("playoff_meetings", models.PositiveSmallIntegerField(default=0)),
                ("largest_margin", models.FloatField(default=0.0)),
                (
                    "manager_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="h2h_as_a",
                        to="league.manager",
                    ),
                ),
                (
                    "manager_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="h2h_as_b",
                        to="league.manager",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manager_a", "manager_b"), name="uniq_h2h_pair"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerWeekStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gsis_id", models.CharField(db_index=True, max_length=32)),
                ("season", models.PositiveIntegerField()),
                ("week", models.PositiveSmallIntegerField()),
                ("position", models.CharField(blank=True, max_length=8)),
                ("team", models.CharField(blank=True, max_length=8)),
                ("fantasy_points", models.FloatField(default=0.0)),
                ("fantasy_points_ppr", models.FloatField(default=0.0)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="week_stats",
                        to="league.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["season", "gsis_id"],
                        name="league_play_season_d58f09_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gsis_id", "season", "week"), name="uniq_player_week"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                fields=("league", "year"), name="uniq_league_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="award",
            constraint=models.UniqueConstraint(
                fields=("season", "slug"), name="uniq_award"
            ),
        ),
        migrations.AddConstraint(
            model_name="seasontrend",
            constraint=models.UniqueConstraint(
                fields=("season", "key"), name="uniq_season_trend"
            ),
        ),
        migrations.AddConstraint(
            model_name="teamseason",
            constraint=models.UniqueConstraint(
                fields=("season", "espn_team_id"), name="uniq_season_team"
            ),
        ),
        migrations.AddIndex(
            model_name="matchup",
            index=models.Index(
                fields=["season", "week"], name="league_matc_season__31cc9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchup",
            constraint=models.UniqueConstraint(
                fields=("season", "week", "home"), name="uniq_matchup_home_week"
            ),
        ),
        migrations.AddConstraint(
            model_name="managerseasonstats",
            constraint=models.UniqueConstraint(
                fields=("manager", "season"), name="uniq_manager_season_stats"
            ),
        ),
        migrations.AddIndex(
            model_name="lineupslot",
            index=models.Index(
                fields=["week", "slot"], name="league_line_week_7a0a75_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lineupslot",
            constraint=models.UniqueConstraint(
                fields=("team_season", "week", "player"), name="uniq_lineup_slot"
            ),
        ),
        migrations.AddConstraint(
            model_name="draftpick",
            constraint=models.UniqueConstraint(
                fields=("season", "overall_pick"), name="uniq_draft_overall"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["season", "week"], name="league_tran_season__b19b88_idx"
            ),
        ),
    ]
