# Generated by Django 5.1.15 on 2026-07-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerManagerSeasonValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.FloatField(default=0.0)),
                ('started_points', models.FloatField(default=0.0)),
                ('bench_points', models.FloatField(default=0.0)),
                ('weeks_rostered', models.PositiveSmallIntegerField(default=0)),
                ('weeks_started', models.PositiveSmallIntegerField(default=0)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_values', to='league.manager')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_values', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_manager_values', to='league.season')),
            ],
            options={
                'indexes': [models.Index(fields=['manager', 'season'], name='league_play_manager_029d8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'manager', 'season'), name='uniq_player_manager_season_value')],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='', max_length=16)),
                ('total_points', models.FloatField(default=0.0)),
                ('started_points', models.FloatField(default=0.0)),
                ('bench_points', models.FloatField(default=0.0)),
                ('weeks_rostered', models.PositiveSmallIntegerField(default=0)),
                ('weeks_started', models.PositiveSmallIntegerField(default=0)),
                ('points_over_replacement', models.FloatField(default=0.0)),
                ('position_rank', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_values', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_values', to='league.season')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'position'], name='league_play_season__d255c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'season'), name='uniq_player_season_value')],
            },
        ),
    ]
