# Generated by Django 5.1.15 on 2026-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_manager_merged_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerseasonstats',
            name='bench_losses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
