# Generated by Django 5.1.15 on 2026-08-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_managerseasonstats_bench_losses'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
