# Generated by Django 5.1.15 on 2026-08-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_playerprojection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('season', models.PositiveIntegerField()),
                ('player_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=8)),
                ('team', models.CharField(blank=True, max_length=8)),
                ('rank_overall', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_pos', models.PositiveIntegerField(blank=True, null=True)),
                ('tier', models.CharField(blank=True, max_length=8)),
                ('adp_overall', models.FloatField(blank=True, null=True)),
                ('espn_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('risk', models.FloatField(blank=True, null=True)),
                ('upside', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'source'], name='league_expe_season_5c66b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'season', 'position', 'player_name'), name='uniq_expert_rank_row')],
            },
        ),
    ]
