# Generated by Django 5.1.15 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("league", "0007_expertranking"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(default="nflsim", max_length=32)),
                ("schema_version", models.PositiveSmallIntegerField()),
                ("season", models.PositiveIntegerField()),
                ("scoring", models.CharField(max_length=64)),
                ("league_teams", models.PositiveSmallIntegerField()),
                ("simulations", models.PositiveIntegerField()),
                ("generated_at", models.DateTimeField()),
                ("imported_at", models.DateTimeField(auto_now=True)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [models.Index(fields=["season", "league_teams"], name="league_simu_season_37699e_idx")],
                "constraints": [models.UniqueConstraint(fields=("source", "season", "scoring", "league_teams"), name="uniq_simulation_snapshot")],
            },
        ),
    ]
